---
title: "P8105 Homework 3"
author: "Junhui Mi"
date: "2019/10/8"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%")

library(tidyverse)
library(ggridges)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Problem 1

```{r}

library(p8105.datasets)
data("instacart")
instacart %>%
  group_by(aisle) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  top_n(1)

length(pull(instacart, aisle))

instacart %>%
  group_by(aisle) %>%
  summarize(n = n()) %>%
  filter(n > 10000) %>%
  arrange(n) %>%
  ggplot(aes(x = aisle, y = n)) + 
  geom_point(alpha = .5) + 
  theme(axis.text.x = element_text(angle = 90)) +
  labs(
    title = "Aisles order plot",
    x = "Aisles",
    y = "Number of items ordered",
    caption = "Data from instacart")

instacart %>%
  filter(aisle == "baking ingredients" | aisle == "dog food care" |
           aisle == "packaged vegetables fruits") %>%
  group_by(aisle, product_name) %>%
  summarize(number_of_selling = n()) %>%
  arrange(desc(number_of_selling)) %>%
  ungroup() %>%
  group_by(aisle) %>%
  top_n(3) %>%
  knitr::kable()
```

# Problem 2

```{r pressure, echo=FALSE}

```

