---
title: "P8105 Homework 3"
author: "Junhui Mi"
date: "2019/10/8"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%")

library(tidyverse)
library(ggridges)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Problem 1

```{r}
library(p8105.datasets)
data("instacart")
instacart %>%
  group_by(aisle) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  head(1) %>%
  knitr::kable()

instacart %>%
  distinct(aisle) %>%
  nrow()

instacart %>%
  group_by(aisle) %>%
  summarize(n = n()) %>%
  filter(n > 10000) %>%
  ggplot(aes(x = reorder(aisle, n), y = n)) + 
  geom_col(fill = "blue") + 
  labs(
    title = "Plot of Aisles Order Number",
    x = "Aisles",
    y = "Number of items ordered",
    caption = "Data from instacart") +
  coord_flip()

instacart %>%
  filter(aisle %in% c("baking ingredients", "dog food care", 
                      "packaged vegetables fruits")) %>%
  group_by(aisle, product_name) %>%
  summarize(number_of_selling = n()) %>%
  arrange(desc(number_of_selling)) %>%
  top_n(3) %>%
  knitr::kable(caption = "Three most popular products",
               col.names = c("Product category", "Product name",
                             "Number of selling"))

instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(meantime_of_selling = mean(order_hour_of_day)) %>%
  pivot_wider(
    names_from = order_dow,
    values_from = meantime_of_selling
  ) %>%
  knitr::kable(caption = "Mean Order time of two product", 
               col.names = c("Product Name", "Sunday", "Monday", "Tuesday",
                             "Wednesday", "Thursday", "Friday", "Saturday"),
               digits = 0)
```



# Problem 2

```{r pressure, echo=FALSE}
library(p8105.datasets)
data("brfss_smart2010")
brfss_ordered = brfss_smart2010 %>%
  janitor::clean_names() %>%
  filter(topic == "Overall Health",
         response %in% c("Excellent","Very good", "Good","Fair","Poor")) %>%
  mutate(response = forcats::fct_relevel(response, 
                                        c("Poor", "Fair", "Good", 
                                          "Very good","Excellent")))

brfss_ordered %>%
 filter(year == 2002) %>%
  group_by(locationabbr, locationdesc) %>%
  summarize(n = n()) %>%
  group_by(locationabbr) %>%
  summarize(observed_locations_2002 = n()) %>%
  filter(observed_locations_2002 >= 7)

brfss_ordered %>%
 filter(year == 2010) %>%
  group_by(locationabbr, locationdesc) %>%
  summarize(n = n()) %>%
  group_by(locationabbr) %>%
  summarize(observed_locations_2010 = n()) %>%
  filter(observed_locations_2010 >= 7)

brfss_average = brfss_ordered %>%
  filter(response == "Excellent") %>%
  group_by(year, locationabbr) %>%
  summarize(average_value = mean(data_value, na.omit = TRUE))
brfss_average %>%
  mutate(state = locationabbr) %>%
  ggplot(aes(x = year, y = average_value, color = state)) + 
    geom_point() + geom_line() + theme(legend.position = "bottom") +
  labs(title = "Average value between 2002 and 2010 within state",
       caption = "Data from BRFSS")

brfss_ordered %>%
  filter(year %in% c(2006, 2010),
         locationabbr == "NY") %>%
  mutate(county = locationdesc) %>%
  ggplot(aes(x = response, y = data_value, fill = county)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.5) +
  facet_grid(~year) + 
  viridis::scale_fill_viridis(discrete = TRUE) +
  theme(legend.position = "bottom") +
  labs(title = "Distribution of responses among counties in NY State",
       caption = "Data from BRFSS")
  
  
```

